services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: renessans_api
    restart: always
    ports:
      - "9099:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=renessans;Username=postgres;Password=postgres
    volumes:
      - ./backend/RenessansAPI/wwwroot/images:/app/wwwroot/images
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: renessans_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=renessans
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backup:
    build:
      context: .
      dockerfile: ./backup/Dockerfile
    container_name: renessans_backup
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=renessans
    volumes:
      - ./backups:/backups
      - ./backend/RenessansAPI/wwwroot/images:/data/images:ro
    depends_on:
      - db

volumes:
  postgres_data:
